/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SortiesRouteImport } from './routes/sorties'
import { Route as RecrutementsRouteImport } from './routes/recrutements'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as FichesPosteRouteImport } from './routes/fiches-poste'
import { Route as EntreesRouteImport } from './routes/entrees'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CollaborateursRouteImport } from './routes/collaborateurs'
import { Route as IndexRouteImport } from './routes/index'

const SortiesRoute = SortiesRouteImport.update({
  id: '/sorties',
  path: '/sorties',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementsRoute = RecrutementsRouteImport.update({
  id: '/recrutements',
  path: '/recrutements',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const FichesPosteRoute = FichesPosteRouteImport.update({
  id: '/fiches-poste',
  path: '/fiches-poste',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreesRoute = EntreesRouteImport.update({
  id: '/entrees',
  path: '/entrees',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateursRoute = CollaborateursRouteImport.update({
  id: '/collaborateurs',
  path: '/collaborateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collaborateurs': typeof CollaborateursRoute
  '/commandes': typeof CommandesRoute
  '/entrees': typeof EntreesRoute
  '/fiches-poste': typeof FichesPosteRoute
  '/pipeline': typeof PipelineRoute
  '/recrutements': typeof RecrutementsRoute
  '/sorties': typeof SortiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collaborateurs': typeof CollaborateursRoute
  '/commandes': typeof CommandesRoute
  '/entrees': typeof EntreesRoute
  '/fiches-poste': typeof FichesPosteRoute
  '/pipeline': typeof PipelineRoute
  '/recrutements': typeof RecrutementsRoute
  '/sorties': typeof SortiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collaborateurs': typeof CollaborateursRoute
  '/commandes': typeof CommandesRoute
  '/entrees': typeof EntreesRoute
  '/fiches-poste': typeof FichesPosteRoute
  '/pipeline': typeof PipelineRoute
  '/recrutements': typeof RecrutementsRoute
  '/sorties': typeof SortiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collaborateurs'
    | '/commandes'
    | '/entrees'
    | '/fiches-poste'
    | '/pipeline'
    | '/recrutements'
    | '/sorties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collaborateurs'
    | '/commandes'
    | '/entrees'
    | '/fiches-poste'
    | '/pipeline'
    | '/recrutements'
    | '/sorties'
  id:
    | '__root__'
    | '/'
    | '/collaborateurs'
    | '/commandes'
    | '/entrees'
    | '/fiches-poste'
    | '/pipeline'
    | '/recrutements'
    | '/sorties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollaborateursRoute: typeof CollaborateursRoute
  CommandesRoute: typeof CommandesRoute
  EntreesRoute: typeof EntreesRoute
  FichesPosteRoute: typeof FichesPosteRoute
  PipelineRoute: typeof PipelineRoute
  RecrutementsRoute: typeof RecrutementsRoute
  SortiesRoute: typeof SortiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sorties': {
      id: '/sorties'
      path: '/sorties'
      fullPath: '/sorties'
      preLoaderRoute: typeof SortiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutements': {
      id: '/recrutements'
      path: '/recrutements'
      fullPath: '/recrutements'
      preLoaderRoute: typeof RecrutementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiches-poste': {
      id: '/fiches-poste'
      path: '/fiches-poste'
      fullPath: '/fiches-poste'
      preLoaderRoute: typeof FichesPosteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrees': {
      id: '/entrees'
      path: '/entrees'
      fullPath: '/entrees'
      preLoaderRoute: typeof EntreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborateurs': {
      id: '/collaborateurs'
      path: '/collaborateurs'
      fullPath: '/collaborateurs'
      preLoaderRoute: typeof CollaborateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollaborateursRoute: CollaborateursRoute,
  CommandesRoute: CommandesRoute,
  EntreesRoute: EntreesRoute,
  FichesPosteRoute: FichesPosteRoute,
  PipelineRoute: PipelineRoute,
  RecrutementsRoute: RecrutementsRoute,
  SortiesRoute: SortiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
